In [7]:
!pip install duckdb
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: duckdb in c:\users\thayl\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.5.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: C:\Users\thayl\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\thayl\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\thayl\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\thayl\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   ----------------- ---------------------- 4.2/9.7 MB 19.4 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.7 MB 14.5 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 16.4 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.1 tzdata-2025.3

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: C:\Users\thayl\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [20]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [22]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [33]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo']= arquivo
df['data_ingestao']= data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo           data_ingestao
0  10004    SERRA  BT10    100    100  z0019_2.csv 2026-03-19 23:34:48.001
1  10005  MACHADO  BT50    100   1500  z0019_2.csv 2026-03-19 23:34:48.001
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-03-19 23:34:48.001

In [30]:
con.execute("""
CREATE TABLE IF NOT EXISTS bronze_z0019(
    NATBR VARCHAR,
    MAKTX VARCHAR,
    WERKS VARCHAR,
    MAINS VARCHAR,
    LABST VARCHAR,
    nome_arquivo VARCHAR,
    data_ingestao TIMESTAMP
            )
""")

In [34]:
con.execute("INSERT INTO bronze_z0019 SELECT * FROM df")

In [35]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-03-19 23:33:39.641310
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-03-19 23:33:39.641310
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-03-19 23:33:39.641310
3  10004     SERRA  BT10   100   100  z0019_2.csv 2026-03-19 23:34:48.001000
4  10005   MACHADO  BT50   100  1500  z0019_2.csv 2026-03-19 23:34:48.001000
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-03-19 23:34:48.001000

In [ ]:
#con.execute("DROP TABLE bronze_z0019")

In [15]:
#con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [36]:
con.close()